### ISSUE TITLE
After upgrading JPMML to version 1.6.4, I can only use xsd file version 4.4 for schema validation.

### ISSUE THREAD

**Issue by sasahardi997** [jpmml/jpmml-model#40]
Before upgrading, I was using JPMML version 1.4.15. I used to extract a PMML version from the pmml document and then to add the corresponding xsd file to the schema validation.

After upgrading JPMML to version 1.6.4, I'm no longer able to do that. I can only use my custom 4.4.xsd or the original one using JAXButil.getSchema() which uses the original 4-4.xsd file from the pmml-model jar.

If I try to use some version of xsd file below 4.4, I'm getting the following error:

ERROR: PMML #69111 - Failed to create the PMML data model.

Schema validation errors:
cvc-elt.1.a: Cannot find the declaration of element 'PMML'.
Technical Information:
ERROR: PMML #69114 - The PMML XML:

Surprisingly, all my tests pass when I use 4.4.xsd for schema validation even if I use **different versions of pmml documents** (3.0, 3.2, 4.0, 4.1, 4.2 and 4.3). 
Do we have guarantee that all the versions of pmml documents will work with 4.4.xsd schema validation?
Is that the expected and planned behavor?
Do I miss something in the code that will allow to use xsd file version below 4.4?

My code (refactored to work only with xsd file version 4.4, it fails with the xsd versions below 4.4):
```
  public static PMML createPMML(String pmmlXML) throws PMMLException
	  {
		ValidationEventHandlerImpl errInserter = new ValidationEventHandlerImpl();
		PMML answer = null;
		try
		{				
			pmmlXML = pmmlXML.trim();
			byte[] pmmlBytes = pmmlXML.getBytes();

			InputStream is = new ByteArrayInputStream(pmmlBytes);
			ImportFilter filter = new ImportFilter();
			Source source = SAXUtil.createFilteredSource(is, filter);

			Unmarshaller unmarshaller = JAXBUtil.createUnmarshaller();
			unmarshaller.setSchema(getSchema(pmmlXML));
			unmarshaller.setEventHandler(errInserter);

			answer = (PMML)unmarshaller.unmarshal(source);
		}
		catch(UnmarshalException ex)
		{
		//Error handling...
		}
		return answer;
	}

	public static Schema getSchema(String pmmlXML ) throws SAXException
	{
		Schema schema;

		URL url = com.example.pmml.services.impl.PMMLEvaluator.class.getResource("/"+ xsdFile);

		if(url == null)
		{
			PMMLLogger.processTechLogWrite(ERROR, String.format(
					"Cannot open XSD for PMML version '4.4' for the PMML XML '%s'.", pmmlXML));
			throw new RuntimeException("Cannot open XSD for PMML version 4.4.");
		}

		SchemaFactory schemaFactory = SchemaFactory.newInstance(XMLConstants.W3C_XML_SCHEMA_NS_URI);

		schema = schemaFactory.newSchema(url);

		return schema;
	}
```

**Comment by vruusmann** [comment]
The upgrade from 1.4.X to 1.6.X includes replacing "Java XML Binding" libraries (`javax.xml.bind.*`) with "Jakarta XML Binding" (`jakarta.xml.bind.*`)  libraries.

> Schema validation errors:
> cvc-elt.1.a: Cannot find the declaration of element 'PMML'.

This error is coming from the underlying Jakarta XML Binding layer.

Quick googling suggest that the actual namespace of the PMML element does not match the expected one.

One word of caution. Currently there exist two sets of PMML XSD files, which differ by the URL protocol part. The correct set uses `http` protocol (eg. `http://www.dmg.org/PMML-4_4`) whereas the fake set uses the `https` protocol (eg. `https://www.dmg.org/PMML-4_4`).

The fake set of PMML XSD files came into existing when DMG.org migrated their website from HTTP to HTTPS, and thoughtlessly run a "replace all" command on all its site contents too. They should have excluded PMML XSD files from this replace, because XML namespace prefixes are real identifiers not URLs, which cannot be changed after 15 years of use. 

See also https://github.com/jpmml/jpmml-model/issues/38

**Comment by vruusmann** [comment]
Closing this issue, as it has been moved to a private e-mail conversation.

**Comment by sasahardi997** [comment]
Hi Villu, thank you for your quick response, I really appreciate it!

I have a few additional questions:

1.Is it better to use this approach to validate the PMML document? As I
understood, the usage will accept any PMML version document (f.e. 4.1), and
it will be validated against 4.4.xsd. And that is how it should be, I
should not try to fix schema manually to use older xsd documents, right?

answer = new LoadingModelEvaluatorBuilder()
      .setFilters(Arrays.asList(new ImportFilter(), new OutputFieldFixer()))
      .setValidationEventHandler(errInserter)
      .setSchema(JAXBUtil.getSchema())
      .load(is)
      .getPMML();


2. I want to add dataType to the OutputField, because in some older
documents, dataType is missing since that field was optional until xsd 4.3.
I created a filter and it works, but it always add "string" dataType. Is it
possible to somehow set the predicted/correct dataType to he field? Do we
have some example of that?

public class OutputFieldFixer extends XMLFilterImpl {

    @Override
    public void startElement(String uri, String localName, String
qName, Attributes attributes) throws SAXException {
        if("OutputField".equals(localName)) {
            boolean dataTypeMissing = true;

            for(int i = 0; i < attributes.getLength(); i++) {
                if("dataType".equals(attributes.getLocalName(i))) {
                    dataTypeMissing = false;
                    break;
                }
            }

            if(dataTypeMissing) {
                AttributesImpl newAttributes = new AttributesImpl(attributes);

                newAttributes.addAttribute("", "dataType", "dataType",
"CDATA", "string");
                super.startElement(uri, localName, qName, newAttributes);
                return;
            }
        }
        super.startElement(uri, localName, qName, attributes);
    }
}


That you so much!

All the best,
Aleksandar Hardi.

**Comment by vruusmann** [comment]
> I can only use my custom 4.4.xsd or the original one using JAXButil.getSchema() which uses the original 4-4.xsd file from the pmml-model jar.

The PMML 4.4 XSD that is embedded into `org.jpmml:pmml-model` artifact contains some JPMML-specific extension elements and extension attributes. By convention, all extension elements are prefixed with `X-` (uppercase "X") and all extension elements with `x-` (lowercase "x").

For example, this XSD states that all model elements may carry an `x-mathContext` extension element, which specifies the default numeric precision for carrying out numeric computations within this element (eg. 64-bit float vs 32-bit float).

If you use your own PMML 4.4 XSD for validation, then all such extensions will be reported as errors. Or, at minimum, you could configure your SAX validator so that these kinds of errors will be re-classified from "fatal" to "warning".

**Comment by vruusmann** [comment]
> Is it better to use this approach to validate the PMML document?
>
>``` java
>answer = new LoadingModelEvaluatorBuilder()
>      .setFilters(Arrays.asList(new ImportFilter(), new OutputFieldFixer()))
>      .setValidationEventHandler(errInserter)
>      .setSchema(JAXBUtil.getSchema())
>      .load(is)
>      .getPMML();
>```

So you're basically creating an `org.jpmml.evaluator.Evaluator` instance using the `LoadingModelEvaluatorBuilder#load(InputStream)` method, but are then throwing it away, because you then invoke the `Evaluator#getPMML()` method on it (the value of the `answer` variable will be an `org.dmg.pmml.PMML` object)?

All the PMML streaming, filtering and validation happens inside the `LoadingModelEvaluatorBuilder#load(InputStream)` method. If it passes cleanly, then the input was valid according to PMML 4.4 XSD. Invoking `Evaluator#getPMML()` does not do anything useful in this context. 

You better create some unit tests that use known-bad PMML documents as inputs.

> I want to add dataType to the OutputField. I created a filter and it works, but it always add "string" dataType. Is it possible to somehow set the predicted/correct dataType to he field?

The `string` data type is a reasonable default, because it is possible to format any other value (eg. numeric, boolean, datetime) into a string value, and then parse it back to the original value.

However, unnecessary conversions to/from string should be avoided.

When talking about the `OutputField` element specifically, then you may observe its `feature` attribute for some type hints. For example, the "probability" result feature (`Output@feature="probability"`) should be assigned to some numeric data type (usually `double`). Or, in case of the "transformedValue" result feature you may inspect the enclosed Expression element, and see if you can copy its `dataType` attribute, or see what it's doing there (eg. is it performing a numeric computation?).

If the `OutputField` element has a `opType` attribute defined, then you can use this information to eliminate some options. For example, if the operational type is `continuous`, then the data type should be numeric, not string (the concept of a continuous string is non-sensical).
