### ISSUE TITLE
SimplePredicate doesn't prepare parsed value

### ISSUE THREAD

**Issue by Spikhalskiy** [jpmml/jpmml-model#6]
Hi,

Profiled garbage and CPU consumption of jpmml-evaluator in our project and found that SimplePredicate contains only string value and doesn't prepare parsed value. Additionally, it only implemented HasValue and doesn't implement HasParsedValue.

As a result, when we compare FieldValue from evaluator's input with SimplePredicate in ```FieldValue#compareTo(HasValue hasValue)``` we always go to ```compareToString(hasValue.getValue())``` branch with producing garbage and loosing CPU on parsing SimplePredicate's value on each check.

No reasons actually for such design, because at least in the case of trees we have full information about SimplePredicate's value type in tree description. For example:
```<DerivedField name="x12" optype="continuous" dataType="float">```
In worst case - SimplePredicate could prepare parsed results just for all types on ```setValue(String value)``` to return them from HasParsedValue's method.

Looks like this improvement could potentially reduce garbage and save a significant amount of CPU time.

**Comment by vruusmann** [comment]
The `pmml-extension` module of the JPMML-Evaluator library contains class `org.jpmml.evaluator.RichSimplePredicate`, which provides the requested "cache the parsing result" functionality.

The `org.jpmml.evaluator.HasParsedValue` optimization takes effect if you replace "ordinary" `org.dmg.pmml.SimplePredicate` objects with `org.jpmml.evaluator.RichSimplePredicate` objects. It can be done in two ways:
1. Instantiate JAXB unmarshaller using the `org.jpmml.evaluator.RichObjectFactory` class.
2. Rewrite existing tree model object by applying the `org.jpmml.evaluator.visitors.PredicateOptimizer` visitor class to it.

Interface `org.jpmml.evaluator.HasParsedValue` is specific to the JPMML-Evaluator library, and cannot be transferred to the JPMML-Model library due to internal dependencies and licensing restrictions.

Of course, you are always welcome to build your own `HasParsedValue` implementation. The existing system addresses the general case, but if you are dealing with some special case (eg. possibility to intern parsing results), then you can probably attain even better performance and memory usage stats.
